const INCREMENT_COUNT = "INCREMENT_COUNT";
const DECREMENT_COUNT = "DECREMENT_COUNT";

const REQUEST_ARTWORK_JSON = "REQUEST_ARTWORK_JSON";
const RECEIVE_ARTWORK_JSON = "RECEIVE_ARTWORK_JSON";

export default {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  REQUEST_ARTWORK_POSTS,
  RECEIVE_ARTWORK_POSTS
};
